require 'csv'

namespace :charity do
  desc "Charity data import"
  task import: :environment do
    CSV.foreach("20150617_DataDotGov.csv") do |row|
      print '.'
      Charity.create(abn: row[0], charity_legal_name: row[1] ? row[1].encode!('UTF-8', 'binary', invalid: :replace, undef: :replace, replace: '-') : row[1], other_organisation_names: row[2] ? row[2].encode!('UTF-8', 'binary', invalid: :replace, undef: :replace, replace: '-') : row[2], operating_countries: row[3] ? row[3].encode!('UTF-8', 'binary', invalid: :replace, undef: :replace, replace: '-') : row[3], address_type: row[4] ? row[4].encode!('UTF-8', 'binary', invalid: :replace, undef: :replace, replace: '-') : row[4], address_line_1: row[5] ? row[5].encode!('UTF-8', 'binary', invalid: :replace, undef: :replace, replace: '-') : row[5], address_line_2: row[6], address_line_3: row[7], town_city: row[8], state: row[9], postcode: row[10], country: row[11], charity_website: row[12], registration_date: row[13], date_organisation_established: row[14], charity_size: row[15], number_of_responsible_persons: row[16], financial_year_end: row[17], operates_in_act: row[18], operates_in_nsw: row[19], operates_in_nt: row[20], operates_in_qld: row[21], operates_in_sa: row[22], operates_in_tas: row[23], operates_in_vic: row[24], operates_in_wa: row[25], pbi: row[26], hpc: row[27], preventing_or_relieving_suffering_of_animals: row[28], advancing_culture: row[29], advancing_education: row[30], advancing_health: row[31], promote_or_oppose_a_change_to_law__government_poll_or_prac: row[32], advancing_natual_environment: row[33], promoting_or_protecting_human_rights: row[34], purposes_beneficial_to_ther_general_public_and_other_analogous: row[35], promoting_reconciliation__mutual_respect_and_tolerance: row[36], advancing_religion: row[37], advancing_social_or_public_welfare: row[38], advancing_security_or_safety_of_australia_or_australian_public: row[39], another_purpose_beneficial_to_the_community: row[40], aboriginal_or_tsi: row[41], aged_persons: row[42], children: row[43], communities_overseas: row[44], ethnic_groups: row[45], gay__lesbian__bisexual: row[46], general_community_in_australia: row[47], men: row[48], migrants__refugees_or_asylum_seekers: row[49], pre_post_release_offenders: row[50], people_with_chronic_illness: row[51], people_with_disabilities: row[52], people_at_risk_of_homelessness: row[53], unemployed_persons: row[54], veterans_or_their_families: row[55], victims_of_crime: row[56], victims_of_disasters: row[57], women: row[58], youth: row[59])
    end
  end
end
